"""Presence Protocol — Python types and validators (version 0.1.0)."""

from presence_protocol.events import (
    PROTOCOL_VERSION,
    Action,
    ActionStatus,
    Animation,
    Ask,
    AskKind,
    AskResponse,
    AvatarChanged,
    AvatarState,
    ControlMessage,
    Done,
    ErrorEvent,
    Interrupt,
    PresenceEvent,
    SessionReady,
    SetAvatar,
    SetVoice,
    SpeakDelta,
    Speaker,
    Status,
    Think,
    Transcript,
    UserTurn,
    VoiceChanged,
    is_valid_control_message,
    is_valid_presence_event,
    parse_control_message,
    parse_presence_event,
    to_wire,
)

__all__ = [
    "PROTOCOL_VERSION",
    # shared
    "Animation",
    "Speaker",
    "ActionStatus",
    "AskKind",
    # downstream
    "PresenceEvent",
    "SessionReady",
    "AvatarState",
    "SpeakDelta",
    "Transcript",
    "Think",
    "Action",
    "Ask",
    "Status",
    "AvatarChanged",
    "VoiceChanged",
    "ErrorEvent",
    "Done",
    # upstream
    "ControlMessage",
    "UserTurn",
    "Interrupt",
    "AskResponse",
    "SetAvatar",
    "SetVoice",
    # helpers
    "parse_presence_event",
    "parse_control_message",
    "is_valid_presence_event",
    "is_valid_control_message",
    "to_wire",
]
